spring:
  application:
    name: BananaInvoicesService
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
app.jwt.secret: SECRET-KEY-VALUE

---
spring:
  sql.init.mode: always
  profiles: dev
  application:
    name: BananaInvoicesService
  datasource:
    url: "jdbc:h2:file:./invoicesdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  port: 9090

#debug: true
logging:
  path: /var/tmp/
  file: /var/tmp/mylog.log
  level:
    root: INFO


---
spring:
  profiles: prod
  application:
    name: BananaInvoicesService
  datasource:
    url: "jdbc:mysql://localhost/invoices?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: invoices_user
    password: inv123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      generate-ddl: false

spring.security.oauth2.resourceserver.jwt.issuer-uri: https://auth-server:9443


server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: pa55wrd
    keyStoreType: PKCS12
    keyAlias: tomcat
security.require-ssl: true

security.oauth: false # If true OAuth security is activated, else JWT
