server.port: 8081

spring.cloud.stream.bindings.input.destination: demo-strm # old way
spring.cloud.stream.bindings.onReceive-in-0.destination: demo-strm
spring.cloud.stream.bindings.logIt-in-0.destination: demo-strm

# spring.cloud.function.definition: onReceive;logIt

# for scdf
spring.cloud.stream.function.bindings.onReceive-in-0: input
spring.cloud.stream.function.bindings.logIt-in-0: input


