spring.cloud.stream.bindings:
  input.destination: my-src # old way
  output.destination: my-proc # old way
  convertToUppercase-in-0.destination: my-src # new way
  convertToUppercase-out-0.destination: my-proc # new way

