server.port: 8082

spring.cloud.stream.bindings:
  input.destination: my-src # old way
  output.destination: my-proc # old way
  convertToUppercase-in-0.destination: my-src # new way
  convertToUppercase-out-0.destination: my-proc # new way
  processIt-in-0.destination: my-src # new way
  processIt-out-0.destination: my-proc # new way

# for scdf
spring.cloud.stream.function.bindings.convertToUppercase-in-0: input
spring.cloud.stream.function.bindings.convertToUppercase-out-0: output
spring.cloud.stream.function.bindings.processIt-in-0: input
spring.cloud.stream.function.bindings.processIt-out-0: output