spring:
  application:
    name: BananaInvoicesService

# AWS
cloud.aws:
  region:
    auto: false
    static: us-east-1
    use-default-aws-region-chain: true
  stack: false
  stack.auto: false
  #  credentials.instance-profile: false
  credentials:
    access-key: AKIAZRFGKQIDQQYG3JMQ
    secret-key: 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

# Logging
logging:
  level:
    com.amazonaws:
      internal.InstanceMetadataServiceResourceFetcher: error
      util.EC2MetadataUtils: error

---
spring:
  config.activate.on-profile: dev
  devtools.restart.enabled: true
  application:
    name: BananaInvoicesService
  sql.init.mode: always
  datasource:
    url: "jdbc:h2:file:./invoicesdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  batch.jdbc.initialize-schema: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

# batch config
batch.chunk.size: 100
batch.threadPool.size: 20

api.verification.url: "http://localhost:9100/api/v1/invoices/"

# AWS data
inputData.fileExtension: csv
rawdata:
  s3bucket: invoices.samples
  s3object.prefix: toprocess/dev
  s3path: s3://invoices.samples/toprocess/dev

---
spring:
  config.activate.on-profile: prod
  application:
    name: BananaInvoicesService
#  sql.init.mode: always
  datasource:
    url: "jdbc:mysql://localhost/invoices?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: invoices_user
    password: inv123
  batch.jdbc.initialize-schema: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      generate-ddl: false
#    defer-datasource-initialization: true

# batch config
batch.chunk.size: 100
batch.threadPool.size: 20

api.verification.url: "http://localhost:9100/api/v1/invoices/"

# AWS data
inputData.fileExtension: csv
rawdata:
  s3bucket: invoices.samples
  s3object.prefix: toprocess/prod
  s3path: s3://invoices.samples/toprocess/prod
